# Generated by Django 5.1.1 on 2024-09-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('all_service', models.TextField()),
            ],
        ),
    ]
