# Generated by Django 5.1.1 on 2024-09-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_services', '0002_remove_services_all_service_serviceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='service_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
