# Generated by Django 5.1.1 on 2024-09-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_services', '0003_serviceitem_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq', to='all_services.serviceitem')),
            ],
        ),
    ]
