# Generated by Django 5.1.1 on 2024-09-11 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_services', '0004_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='EXCLUDE_SERVICE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ls', models.TextField()),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclude_service', to='all_services.serviceitem')),
            ],
        ),
        migrations.CreateModel(
            name='INCLUDE_SERVICE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ls', models.TextField()),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='include_service', to='all_services.serviceitem')),
            ],
        ),
    ]
