# Generated by Django 5.1.1 on 2024-09-14 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all_services', '0005_exclude_service_include_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Infomation_Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('open_hour', models.CharField(max_length=100)),
                ('footer_description', models.TextField(blank=True, null=True)),
                ('copyright', models.CharField(max_length=100)),
                ('design', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_services.serviceitem')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
