# Generated by Django 5.1.1 on 2024-09-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shongjog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='occupation',
            field=models.CharField(max_length=100),
        ),
    ]
