# Generated by Django 5.1.1 on 2024-09-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shongjog', '0002_remove_registration_email_registration_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='name',
        ),
    ]
