# Generated by Django 5.1.1 on 2024-09-15 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_services', '0005_exclude_service_include_service'),
        ('shongjog', '0003_top_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_product', to='all_services.services'),
        ),
    ]
