# Generated by Django 5.1.1 on 2024-09-15 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_services', '0005_exclude_service_include_service'),
        ('shongjog', '0005_for_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recently_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='recently_view/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_view', to='all_services.services')),
            ],
        ),
    ]
