# Generated by Django 5.1.1 on 2024-09-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shongjog', '0007_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='review/')),
            ],
        ),
    ]
